# 第12章 通过异常处理错误

标签：Java

---

## 基本异常

- 异常情形，从当前环境中跳出，并且把问题提交给上一级环境 throw new NullPointerException() 
- 异常将在一个恰当的异常处理程序中得到解决，它的位置可能离异常被抛出的地方很远，也可能回跨越方法调用栈的许多层次

---

## 捕获异常

- try catch finally 
- 其他部分继续完成
- catch子句只接受一个且仅接受一个特殊类型的参数的方法，只有匹配的catch子句才能得到执行

---

## 创建自定义异常

- 自定义异常类继承Exception，书写构造方法和toString()方法等
- 其他类中 `方法体内throws 自定义异常类{ throw new 自定义异常类(); }` 被 `catch(自定义异常类){调用方法}` 捕获

---

## 重新抛出异常

- 情况是throw e会继续将e返回到高一级环境中进行再次捕获作异常处理
```
catch(Exception e){
System.out.println("Am exception was thrown");
throw e;
}
```

---

## Java标准异常

- Throwable->Error编译时和系统错误/Exception被抛出的基本类型
- RuntimeException运行时错误，若不捕获，最终会直达main()，在程序退出前调用异常的printStackTrace()方法

---

## finally用来做什么

- 把除内存之外的资源恢复到它们的初始状态。这种需要清理的资源包括：已经打开的文件或网络连接，在屏幕上画的图形，甚至可以是外部世界的某个开关...